const data = {
    products:[
        {
            _id: '1',
            name:'Free Guy',
            image:'/images/p1.jpg',
            release:'15-0ct-2021',
            duration:'120 mins',
            rating:4.3,
            countInStock: 4,
            price: 150,
        },
        {
            _id: '2',
            name:'Shang Chi',
            image:'/images/p2.jpg',
            release:'15-0ct-2021',
            duration:'120 mins',
            rating:4.5,
            countInStock: 9,
            price: 150,
        },
        {
            _id: '3',
            name:'Venom',
            image:'/images/p3.jpg',
            release:'15-0ct-2021',
            duration:'120 mins',
            rating:4.0,
            countInStock: 9,
            price: 150,
        },
        {
            _id: '4',
            name:'Black Widow',
            image:'/images/p11.jpg',
            release:'15-0ct-2021',
            duration:'126 mins',
            rating:4.5,
            countInStock: 9,
            price: 150,
        },
        {
            _id: '5',
            name:'Sucide Squad',
            image:'/images/p12.jpg',
            release:'15-0ct-2021',
            duration:'126 mins',
            rating:3.9,
            countInStock: 9,
            price: 150,
        },
        {
            _id: '6',
            name:'Raya and the Last Dragon',
            image:'/images/p13.jpg',
            release:'15-0ct-2021',
            duration:'180 mins',
            rating:4.2,
            countInStock: 9,
            price: 150,
        },
        {
            _id: '7',
            name:'Godzilla vs. Kong',
            image:'/images/p14.jpg',
            release:'15-0ct-2021',
            duration:'180 mins',
            rating:4.3,
            countInStock: 9,
            price: 150,
        },
        {
            _id: '8',
            name:'Cruella',
            image:'/images/p16.jpg',
            release:'15-0ct-2021',
            duration:'120 mins',
            rating:4.4,
            countInStock: 9,
            price: 150,
        },
    ]
}

export default data;